The notebook contain questions about each of these topics:
* Reading data
* Data manipulation
* Basic statistics

# How to Mount the googledrive to access files?

Steps to access the files on GoogleDrive:


1.   Upload the files to Drive
2.   Mount the drive in GoogleColab using code below
3. Access the files

In [ ]:
#Mount the googledrive to access files
from google.colab import drive
drive.mount('/content/drive')
#Path of the file
#'/content/drive/MyDrive/......csv')

Mounted at /content/drive

# Data Explorartion using Pandas DataFrame

In [ ]:
# Question 1: Read the weather dataset (csv) using read_csv function in Pandas
import pandas as pd

#change path based on the dtaa location
dataset_path =

# Data source: https://www.ncdc.noaa.gov/cdo-web/search?datasetid=GHCND

In [ ]:
#How to check the number of rows and columns in DataFrame
print(df.shape)

In [ ]:
# Question 2: Display the first few rows of the DataFrame using the Head method

   YEARMODA  TEMP   MAX   MIN
0  20160601  65.5  73.6  54.7
1  20160602  65.8  80.8  55.0
2  20160603  68.4   NaN  55.6
3  20160604  57.5  70.9  47.3
4  20160605  51.4  58.3  43.2

In [ ]:
# Question 2: How to use the Tail method to display the last few rows of a DataFrame?

    YEARMODA  TEMP   MAX   MIN
25  20160626  69.6  77.7  60.3
26  20160627  60.7  70.0   NaN
27  20160628  65.4  73.0  55.8
28  20160629  65.8  73.2   NaN
29  20160630  65.7  72.7  59.2

In [ ]:
# Question 3: How can we locate any values?

#3.1 Locate values using the first row and third column by index?
df.iloc[0, 2]

#3.2 Retrieve the values of the first row

#3.3 Retrieve the values in the third column

#3.4: Return the values in the column Max

#3.5 Locate values using multiple column names

73.6

In [ ]:
#3.2 Retrieve the values of the first row
df.iloc[0, :]

YEARMODA    20160601.0
TEMP              65.5
MAX               73.6
MIN               54.7
Name: 0, dtype: float64

In [ ]:
#3.3 Retrieve the values in the third column

In [ ]:
# Question 3.4: Return the values in the column Max

In [ ]:
# Question 3.5: Return the values using column names MIN and MAX

In [ ]:
# Question 4: How to filter data in a DataFrame based on a condition?
# Assuming we want to filter rows where the value in 'MIN' temp is greater than 30

In [ ]:
#How to print the column names
print(df.columns.values)

['YEARMODA' 'TEMP' 'MAX' 'MIN']

In [ ]:
#To print the data types
print(df.dtypes)

YEARMODA      int64
TEMP        float64
MAX         float64
MIN         float64
dtype: object

In [ ]:
#How to Select only numeric columns
numeric_columns = df.select_dtypes(include=['number'])
print(numeric_columns)

#How to Select non-numeric columns
non_numeric_columns = df.select_dtypes(exclude=['number'])
print(non_numeric_columns)

# Descriptive statistics

In [ ]:
# Question 5: How to create basic statistics in Pandas using the Describe method?
#Explore the summary statistics

In [ ]:
# To get only the average, use
df.mean()

YEARMODA    2.016062e+07
TEMP        5.973000e+01
MAX         6.804074e+01
MIN         5.125714e+01
dtype: float64

In [ ]:
# How to Check the mean value of a specific column
df['TEMP'].mean()

59.730000000000004

In [ ]:
#to check only the dispersion value for all columns
print(df.std()) #Standard Deviation
print(df.var()) # Variance

YEARMODA    8.803408
TEMP        5.475472
MAX         6.505575
MIN         5.498985
dtype: float64
YEARMODA    77.500000
TEMP        29.980793
MAX         42.322507
MIN         30.238836
dtype: float64

In [ ]:
# Question 6: How to calculate the correlation between columns in a DataFrame?
# Assuming we want to calculate the correlation for all columns