# Week 11:  Data Exploration and Visualization

## Exploratory Data Analysis (EDA)

###1. Import the data
###2. Explore the dataset
###3. Identify data quality issues
###4. data pre-processing
###5. data visualization

## Let the Coding Begin!

In [ ]:
import pandas as pd
import numpy as np

**Mount your googledrive to access files**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

## 1 Reading data from CSV file

#### About the dataset:
This dataset is about the US Permanent Visa Application decisions. The original data covers years 2012 - 2017 and includes information on employer, position, wage offered, job posting history, employee education and past visa history, associated lawyers, and final decision. It was collected and distributed by the US Department of Labor. The dataset we will be using is a small subset of the original dataset.

**Context:** A permanent labor certification issued by the Department of Labor (DOL) allows an employer to hire a foreign worker to work permanently in the United States. In most instances, before the U.S. employer can submit an immigration petition to the Department of Homeland Security's U.S. Citizenship and Immigration Services (USCIS), the employer must obtain a certified labor certification application from the DOL's Employment and Training Administration (ETA). The DOL must certify to the USCIS that there are not sufficient U.S. workers able, willing, qualified and available to accept the job opportunity in the area of intended employment and that employment of the foreign worker will not adversely affect the wages and working conditions of similarly employed U.S. workers.

The goal of the below data analysis is checking the general trend in Visa applications, the most popular citizenships, employers, cities and finally, predicting the application decision based on the chosen features, etc.

The current dataset used in this notebook contains 2000 rows.

***Reference:*** https://www.kaggle.com/elzawie/us-permanent-visa-applications-v1-1

**Question: Read data using Pandas dataframe**

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/430031 notebooks/Week 11/Data/visa_processed.csv") # Reading the file and storing the data inside the variable df
df.head()

,row ID,agent_city,agent_firm_name,agent_state,case_number,case_received_date,case_status,class_of_admission,country_of_citizenship,decision_date,...,employer_postal_code,employer_state,employer_yr_estab,foreign_worker_info_alt_edu_experience,foreign_worker_info_birth_country,foreign_worker_info_city,foreign_worker_info_education,year,decision_year,decision_month
0,133236,houston,foster llp,tx,A-15034-47732,2015-02-20,Certified,H-1B,CHINA,2015-09-08,...,77032,texas,1984.0,Y,CHINA,KATY,Doctorate,2015.0,2015,9
1,30115,woodland hills,trustworthy visa,ca,A-15065-56624,2015-03-10,Certified-Expired,NaN,IRAN,2015-10-09,...,77086,tx,2008.0,NaN,NaN,SHIRAZ,Master's,2015.0,2015,10
2,259290,boston,"fragomen, del rey, bernsen & loewy, llp",ma,A-16166-21556,2016-07-01,Certified,H-1B,CHINA,2016-09-30,...,94089,ca,1957.0,NaN,NaN,SAN JOSE,Master's,2016.0,2016,9
3,196329,chicago,"fragomen, del rey, bernsen & loewy llp",il,A-16117-01841,2016-07-12,Certified,H-1B,INDIA,2016-09-22,...,60601,il,2000.0,NaN,NaN,HARTFORD,Master's,2016.0,2016,9
4,34932,NaN,NaN,NaN,A-15083-61379,2015-03-25,Withdrawn,H-1B,SOUTH KOREA,2015-03-25,...,11050,new york,1991.0,A,SOUTH KOREA,HICKSVILLE,Bachelor's,2015.0,2015,3

### 2 Initial Data Exploration



**Question:** <br/> 1. Find the total number for visa application present in the dataset.
<br/> 2. Find the total number of attributes in the dataset.

**Question:** <br/> 3. What are the names of different attributes?

**Checking for the null data and the data_types of the rows**

**Type**<br>print(df.isnull().any()) and <br> print(df.dtypes)

**Question** <br/> 4. Are there any Null values in the dataset and corresponding to each attribute?
<br/> 5. What is the datatypes of each attribute?

**What will be the decisions based on these results?**


*   Remove columns which has large number of missing values and impute the ones with few
*   Fix attrbiute type

In [ ]:
#Remove all unwanted columns using drop function

In [ ]:
#Fix attribute types



print(df.dtypes)

In [ ]:
#Impute the missing values based on their attrbiute
# Iterate over columns
for col in df.columns:


print(df.isnull().sum())

## 3 Data visualisation

In [ ]:
# Import the MatPlotLib and the Seaborn library
import matplotlib.pyplot as plt
import seaborn as sns # Importing Seaborn library

**Check of the numeric attrbiutes have outliers using BoxPlot**

In [ ]:
#Treatment 1
#Question: Remove all the rows with outliers
# Function to remove outliers from all numeric attributes
print(df.shape)


# Remove outliers from DataFrame by creating remove_outliers function
df_cleaned = remove_outliers(df)
print(df_cleaned.shape)

(2000, 20)
(1560, 20)

In [ ]:
#Treatment 2
#Question: Replace outliers by missing value
print(df.shape)
def remove_outliers(df):
    cleaned_df = df.copy()
    for col in cleaned_df.select_dtypes(include=["number"]).columns:
        Q1 = np.percentile(cleaned_df[col], 25)
        Q3 = np.percentile(cleaned_df[col], 75)
        IQR = Q3 - Q1
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR
        cleaned_df.loc[(cleaned_df[col] < lower_bound) | (cleaned_df[col] > upper_bound), col] = np.nan
    return cleaned_df

# Remove outliers from DataFrame
df_cleaned1 = remove_outliers(df)
print(df_cleaned1.shape)

### 4 Manipulating/Processing data

**Question**:
<br/> How many days does it took to process each visa application?

**Hint:** Find the difference between the case recieved date and decision day

There are two columns having the records in the form of date "decision_date" and "case_received_date".

In [ ]:
from datetime import datetime
data_rcvd = pd.to_datetime(df_cleaned['case_received_date'], format = '%Y-%m-%d')
date_decided = pd.to_datetime(df_cleaned['decision_date'], format = '%Y-%m-%d')
# Calculate the difference between the two dates

New attributes are now added to the dataframe. Let's check the dataframe and the attribute count

**Question**: Generate statistics of the dataset



**Question:** <br/> What is the average processing time for visa application?
<br/> What is the maximum number of days for processing a visa application?

In [ ]:
### Start the code here (~ 2 lines of code)

### 4. More on Initial Data Exploration with Visualization

In [ ]:
# Import the seaborn library as sns and matplotlib.pylot library as plt
### Start the code here (~ 2 lines of code)
import seaborn as sns
import matplotlib.pyplot as plt

**Question**: using bar chart, show the freq of applications per state

In [ ]:
values=df_cleaned['agent_state'].value_counts()
# Create pie chart
plt.figure(figsize=(20, 10))

**Question**: show the boxplot of the total decision plot?

Question: show the histogram of the employer_num_employees?

In [ ]:
#estimate number of bin by square root of total number of rows
nb_bins=round(df_cleaned.shape[0]**0.5)



**Question:** Create a pie chart of the case_status with appropriate title,, Y label, and X label.



**Question:** Check if there is any relationship between employer number and days to decision.