# Week 9 lab - Data pre-processing

In [ ]:
#Mount the googledrive to access files
from google.colab import drive
drive.mount('/content/drive')
#Path of the file
#'/content/drive/MyDrive/......csv')

Mounted at /content/drive

# NSW Australia Property Data
We will import a sample of this large dataset

More info at:
https://www.kaggle.com/datasets/josephcheng123456/nsw-australia-property-data?resource=download

In [ ]:
# Run the code to read a dataset using Pandas?
import pandas as pd

#change path based on your data location
dataset_path = '/content/drive/MyDrive/430031 notebooks/Week 9/Data/nsw_data_property_small.xlsx'
data = pd.read_excel(dataset_path)
# Display the first few rows of the dataframe
print(data.head())

# Explore the dataset to identify the data quality issues

In [ ]:
#Explore the datatypes to check if they are suitable
print(data.dtypes)

#Q: What do you think?
#property_id is it float? post_code is int?

In [ ]:
#Use the astype() method to change the data type of a column
#Complete the code

print(data.dtypes)

## Missing values

In [ ]:
# Question 1: Use isnull() or info() function in Pandas to identify the missing values?


print(missing_values_per_column)

# Data cleaning to solve data quality issues

## Handling missing values by droping rows

In [ ]:
# Question 2: Handle missing values by removing rows with missing values in a Pandas DataFrame using dropna() method?

#assign data to another variable called data_no_missing_values to avoid changes on the same dataset


#Show the stats of null values
print(data_no_missing_values.isnull().sum())

In [ ]:
#How many rows have been removed?
rem_rows=len(data) - len(data_no_missing_values)
print("Number of rows removed:", rem_rows)

Number of rows removed: 70

## Handling missing values by data imputation


*   if the variable is numerical, replace the missing values by mean or median
*   if the variable is non-numerical (categorical), replace the missing values by most frequent value

In [ ]:
# Question 3: Handle missing values by replacing numerical missing values with the mean in a Pandas DataFrame using fillna method?

#identify the numerical variables first


#iterate over each column and relpalce missing by mean


print(data.head())

In [ ]:
# Question 4: How do you handle missing values by replacing categorical missing values with the most frequent value in a Pandas DataFrame?

#identify the non-numeric variables first

#iterate over each column and relpalce missing by mode


print(data.head())

In [ ]:
#Check again the previous code to see if any missing value exist
missing_values_per_column = data.isnull().sum()

# Display the number of missing values per column
missing_values_per_column

## Duplications

In [ ]:
# Question 5: Find the duplicate rows using duplicated() method?

# Check for duplicate rows



print(duplicate_rows.shape)
print(duplicate_rows)

In [ ]:
# Question 6: Find the duplicate columns using duplicated() method?

#Transpose the dataset first then call .duplicated()

## Handling duplicates


*   Remove duplicate rows
*   Remove duplicate columns

In [ ]:
# Question 7: How to Remove duplicate rows drop_duplicates()?

# Remove duplicate rows


# Check duplicates row
print(data[data.duplicated()])

In [ ]:
# Question 8: Remove duplicate columns?

#Transpose the data
df_transposed=data.transpose()


print(data.head())

**Data cleaning has been completed, and there are no more missing values or duplicates in the dataset. It is now ready for data analysis.**